cordova plugin add cordova-plugin-console
cordova plugin add cordova-custom-config
cordova plugin add cordova-plugin-device
cordova plugin add cordova-plugin-iosrtc
cordova plugin add cordova-plugin-media
cordova plugin add android-camera-permission
cordova plugin add cordova-plugin-android-permissions
cordova plugin add cordova-plugin-audiotoggle
cordova plugin add cordova-plugin-audioinput
cordova plugin add cordova-plugin-crosswalk-webview
cordova plugin add cordova-plugin-nativeaudio
